"""Point 10: one command installs everything needed to work on this project.

    python scripts/install_dependencies.py          # runtime only
    python scripts/install_dependencies.py --dev    # + test, lint, benchmark
    python scripts/install_dependencies.py --lock   # regenerate the lock files

The lock files are what make "one command" still true next year: they pin exact
versions, so a fresh checkout in 2028 installs what CI tested with, not whatever
happens to be newest.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEV_LOCK = ROOT / "requirements-dev.lock"


def pip(*args: str) -> None:
    cmd = [sys.executable, "-m", "pip", *args]
    print(f"$ {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, check=True)


def regenerate_lock() -> None:
    """Resolve this project's dependencies in a throwaway virtual environment.

    Freezing the interpreter you happen to be using would pin whatever else is
    installed on that machine - on a workstation that can mean hundreds of
    unrelated packages. A clean environment pins this project and nothing else.
    """
    with tempfile.TemporaryDirectory(prefix="lock-") as tmp:
        env_dir = Path(tmp) / "venv"
        print(f"building a clean environment in {env_dir}", flush=True)
        subprocess.run([sys.executable, "-m", "venv", str(env_dir)], check=True)

        bin_dir = "Scripts" if sys.platform == "win32" else "bin"
        env_python = env_dir / bin_dir / ("python.exe" if sys.platform == "win32" else "python")

        for args in (
            ["-m", "pip", "install", "--upgrade", "--quiet", "pip"],
            ["-m", "pip", "install", "--quiet", f"{ROOT}[dev,release]"],
        ):
            subprocess.run([str(env_python), *args], check=True)

        frozen = subprocess.run(
            [str(env_python), "-m", "pip", "freeze", "--exclude-editable"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout

    # The project itself is installed from source in CI, not from the lock.
    lines = [ln for ln in frozen.splitlines() if ln.strip() and not ln.lower().startswith("repo-quality-template")]
    header = (
        "# Generated by scripts/install_dependencies.py --lock\n"
        "# Resolved in a clean virtual environment. Exact versions CI installs.\n"
        "# Do not edit by hand.\n"
    )
    DEV_LOCK.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {DEV_LOCK.relative_to(ROOT)} ({len(lines)} pinned packages)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dev", action="store_true", help="also install test, lint and benchmark tools")
    parser.add_argument(
        "--lock", action="store_true", help="regenerate requirements-dev.lock from this environment"
    )
    parser.add_argument(
        "--from-lock",
        action="store_true",
        help="install the exact pinned versions instead of resolving",
    )
    args = parser.parse_args()

    if args.lock:
        regenerate_lock()
        return 0

    if args.from_lock:
        if not DEV_LOCK.is_file():
            print(f"error: {DEV_LOCK.name} is missing; run with --lock first", file=sys.stderr)
            return 1
        pip("install", "-r", str(DEV_LOCK))
        pip("install", "-e", ".", "--no-deps")
        return 0

    pip("install", "--upgrade", "pip")
    pip("install", "-e", ".[dev]" if args.dev else ".")
    if args.dev:
        print("\nnext: pre-commit install    # so style is checked on every commit")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
